import { c as create_ssr_component, e as escape, a as each, v as validate_component } from "../../chunks/ssr.js";
import { $ as $format } from "../../chunks/runtime.js";
import { s as subscribe } from "../../chunks/utils.js";
/* empty css                                                 */
const css$5 = {
  code: "img.svelte-1ugrpfl{width:400px;object-fit:cover}.flex-container.svelte-1ugrpfl{display:flex;justify-content:space-around}@media screen and (max-width: 900px){.flex-container.svelte-1ugrpfl{display:block}img.svelte-1ugrpfl{width:100%}}",
  map: '{"version":3,"file":"Welcome.svelte","sources":["Welcome.svelte"],"sourcesContent":["<script>\\n\\timport { _ } from \\"svelte-i18n\\";\\n<\/script>\\n\\n<h1>{$_(\\"welcome.title\\")}</h1>\\n{#each $_(\\"welcome.text\\") as paragraph}\\n\\t<p>{paragraph}</p>\\n{/each}\\n\\n<div class=\\"flex-container\\">\\n\\t<img src=\\"images/reception.jpg\\" alt=\\"Clinic Picture 1\\"/>\\n\\t<img src=\\"images/pano2.jpg\\" alt=\\"Clinic Picture 2\\"/>\\n</div>\\n\\n<style>\\n\\timg{\\n\\t\\twidth: 400px;\\n\\t\\tobject-fit: cover;\\n\\t}\\n\\t.flex-container{\\n\\t\\tdisplay: flex;\\n\\t\\tjustify-content: space-around;\\n\\t}\\n\\t@media screen and (max-width: 900px){\\n\\t\\t.flex-container{\\n\\t\\t\\tdisplay: block;\\n\\t\\t}\\n\\t\\timg{\\n\\t\\t\\twidth: 100%;\\n\\t\\t}\\n\\t}\\n</style>"],"names":[],"mappings":"AAeC,kBAAG,CACF,KAAK,CAAE,KAAK,CACZ,UAAU,CAAE,KACb,CACA,8BAAe,CACd,OAAO,CAAE,IAAI,CACb,eAAe,CAAE,YAClB,CACA,OAAO,MAAM,CAAC,GAAG,CAAC,YAAY,KAAK,CAAC,CACnC,8BAAe,CACd,OAAO,CAAE,KACV,CACA,kBAAG,CACF,KAAK,CAAE,IACR,CACD"}'
};
const Welcome = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let $_, $$unsubscribe__;
  $$unsubscribe__ = subscribe($format, (value) => $_ = value);
  $$result.css.add(css$5);
  $$unsubscribe__();
  return `<h1>${escape($_("welcome.title"))}</h1> ${each($_("welcome.text"), (paragraph) => {
    return `<p>${escape(paragraph)}</p>`;
  })} <div class="flex-container svelte-1ugrpfl" data-svelte-h="svelte-1s2ii86"><img src="images/reception.jpg" alt="Clinic Picture 1" class="svelte-1ugrpfl"> <img src="images/pano2.jpg" alt="Clinic Picture 2" class="svelte-1ugrpfl"> </div>`;
});
const css$4 = {
  code: "a.svelte-5d2wh8{text-decoration:underline;text-align:center;color:black}.grid-container.svelte-5d2wh8{display:grid;grid-template-columns:[row1-start] 34% [row1-end row2-start] \n								34% [row2-end row3-start] 34% [row3-end]}.grid-element.svelte-5d2wh8{text-align:center;font-size:20px;margin:1rem}@media screen and (max-width: 992px){.grid-container.svelte-5d2wh8{grid-template-columns:[row1-start] 50% [row1-end row2-start] \n								50% [row2-end]}}@media screen and (max-width: 720px){.grid-container.svelte-5d2wh8{display:block}}",
  map: '{"version":3,"file":"Services.svelte","sources":["Services.svelte"],"sourcesContent":["<script>\\n\\timport { _ } from \\"svelte-i18n\\";\\n<\/script>\\n\\n<h1>{$_(\\"services.title\\")}</h1>\\n\\n<div class=\\"grid-container\\">\\n\\t{#each $_(\\"services.text\\") as paragraph}\\n\\t\\t<div class=\\"grid-element\\">\\n\\t\\t\\t<a href=\\"/services/{paragraph.href}\\">{paragraph.title}</a>\\n\\t\\t</div>\\n\\t{/each}\\n</div>\\n\\n<style>\\n\\ta{\\n\\t\\ttext-decoration: underline;\\n\\t\\ttext-align: center;\\n\\t\\tcolor: black;\\n\\t}\\n\\t.grid-container{\\n\\t\\tdisplay: grid;\\n\\t\\tgrid-template-columns: [row1-start] 34% [row1-end row2-start] \\n\\t\\t\\t\\t\\t\\t\\t\\t34% [row2-end row3-start] 34% [row3-end];\\n\\t}\\n\\t.grid-element{\\n\\t\\ttext-align: center;\\n\\t\\tfont-size: 20px;\\n\\t\\tmargin: 1rem;\\n\\t}\\n\\t@media screen and (max-width: 992px){\\n\\t\\t.grid-container{\\n\\t\\t\\tgrid-template-columns: [row1-start] 50% [row1-end row2-start] \\n\\t\\t\\t\\t\\t\\t\\t\\t50% [row2-end];\\n\\t\\t}\\n\\t}\\n\\t@media screen and (max-width: 720px){\\n\\t\\t.grid-container{\\n\\t\\t\\tdisplay: block;\\n\\t\\t}\\n\\t}\\n\\n</style>"],"names":[],"mappings":"AAeC,eAAC,CACA,eAAe,CAAE,SAAS,CAC1B,UAAU,CAAE,MAAM,CAClB,KAAK,CAAE,KACR,CACA,6BAAe,CACd,OAAO,CAAE,IAAI,CACb,qBAAqB,CAAE,CAAC,UAAU,CAAC,CAAC,GAAG,CAAC,CAAC,QAAQ,CAAC,UAAU,CAAC;AAC/D,QAAQ,GAAG,CAAC,CAAC,QAAQ,CAAC,UAAU,CAAC,CAAC,GAAG,CAAC,CAAC,QAAQ,CAC9C,CACA,2BAAa,CACZ,UAAU,CAAE,MAAM,CAClB,SAAS,CAAE,IAAI,CACf,MAAM,CAAE,IACT,CACA,OAAO,MAAM,CAAC,GAAG,CAAC,YAAY,KAAK,CAAC,CACnC,6BAAe,CACd,qBAAqB,CAAE,CAAC,UAAU,CAAC,CAAC,GAAG,CAAC,CAAC,QAAQ,CAAC,UAAU,CAAC;AAChE,QAAQ,GAAG,CAAC,CAAC,QAAQ,CACnB,CACD,CACA,OAAO,MAAM,CAAC,GAAG,CAAC,YAAY,KAAK,CAAC,CACnC,6BAAe,CACd,OAAO,CAAE,KACV,CACD"}'
};
const Services = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let $_, $$unsubscribe__;
  $$unsubscribe__ = subscribe($format, (value) => $_ = value);
  $$result.css.add(css$4);
  $$unsubscribe__();
  return `<h1>${escape($_("services.title"))}</h1> <div class="grid-container svelte-5d2wh8">${each($_("services.text"), (paragraph) => {
    return `<div class="grid-element svelte-5d2wh8"><a href="${"/services/" + escape(paragraph.href, true)}" class="svelte-5d2wh8">${escape(paragraph.title)}</a> </div>`;
  })} </div>`;
});
const css$3 = {
  code: "p.svelte-setmz5{margin:0}.grid-container.svelte-setmz5{display:grid;grid-template-columns:[row1-start] 50% [row1-end row2-start] 50% [row2-end]}.grid-element.svelte-setmz5{margin:1rem}@media screen and (max-width: 720px){.grid-container.svelte-setmz5{display:block}}.flex-container.svelte-setmz5{display:flex}img.svelte-setmz5{object-fit:cover;margin:0 1rem}@media screen and (max-width: 900px){.flex-container.svelte-setmz5{display:block}img.svelte-setmz5{width:95%}}@media screen and (min-width: 900px){img.svelte-setmz5{height:250px}}",
  map: '{"version":3,"file":"Team.svelte","sources":["Team.svelte"],"sourcesContent":["<script>\\n\\timport { _ } from \\"svelte-i18n\\";\\n<\/script>\\n\\n<h1>{$_(\\"team.title\\")}</h1>\\n\\n<div class=\\"grid-container\\">\\n\\t{#each $_(\\"team.text\\") as paragraph}\\n\\t\\t<div class=\\"grid-element\\">\\n\\t\\t\\t<h3>{paragraph.name}</h3>\\n\\t\\t\\t{#each paragraph.desc as line}\\n\\t\\t\\t\\t<p>{line}</p>\\n\\t\\t\\t{/each}\\n\\t\\t</div>\\n\\t{/each}\\n</div>\\n\\n<div class=\\"flex-container\\">\\n\\t<img src=\\"images/assistants.jpg\\" alt=\\"Assistants\\">\\n\\t<img src=\\"images/sunee.jpg\\" alt=\\"Dr. Sunee\\">\\n</div>\\n\\n<style>\\n\\tp{\\n\\t\\tmargin: 0;\\n\\t}\\n\\t.grid-container{\\n\\t\\tdisplay: grid;\\n\\t\\tgrid-template-columns: [row1-start] 50% [row1-end row2-start] 50% [row2-end];\\n\\t}\\n\\t.grid-element{\\n\\t\\tmargin: 1rem;\\n\\t}\\n\\t@media screen and (max-width: 720px){\\n\\t\\t.grid-container{\\n\\t\\t\\tdisplay: block;\\n\\t\\t}\\n\\t}\\n\\t.flex-container{\\n\\t\\tdisplay: flex;\\n\\t}\\n\\timg{\\n\\t\\tobject-fit: cover;\\n\\t\\tmargin: 0 1rem;\\n\\t}\\n\\t@media screen and (max-width: 900px){\\n\\t\\t.flex-container{\\n\\t\\t\\tdisplay: block;\\n\\t\\t}\\n\\t\\timg{\\n\\t\\t\\twidth: 95%;\\n\\t\\t}\\n\\t}\\n\\t@media screen and (min-width: 900px){\\n\\t\\timg{\\n\\t\\t\\theight: 250px;\\n\\t\\t}\\n\\t}\\n</style>"],"names":[],"mappings":"AAuBC,eAAC,CACA,MAAM,CAAE,CACT,CACA,6BAAe,CACd,OAAO,CAAE,IAAI,CACb,qBAAqB,CAAE,CAAC,UAAU,CAAC,CAAC,GAAG,CAAC,CAAC,QAAQ,CAAC,UAAU,CAAC,CAAC,GAAG,CAAC,CAAC,QAAQ,CAC5E,CACA,2BAAa,CACZ,MAAM,CAAE,IACT,CACA,OAAO,MAAM,CAAC,GAAG,CAAC,YAAY,KAAK,CAAC,CACnC,6BAAe,CACd,OAAO,CAAE,KACV,CACD,CACA,6BAAe,CACd,OAAO,CAAE,IACV,CACA,iBAAG,CACF,UAAU,CAAE,KAAK,CACjB,MAAM,CAAE,CAAC,CAAC,IACX,CACA,OAAO,MAAM,CAAC,GAAG,CAAC,YAAY,KAAK,CAAC,CACnC,6BAAe,CACd,OAAO,CAAE,KACV,CACA,iBAAG,CACF,KAAK,CAAE,GACR,CACD,CACA,OAAO,MAAM,CAAC,GAAG,CAAC,YAAY,KAAK,CAAC,CACnC,iBAAG,CACF,MAAM,CAAE,KACT,CACD"}'
};
const Team = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let $_, $$unsubscribe__;
  $$unsubscribe__ = subscribe($format, (value) => $_ = value);
  $$result.css.add(css$3);
  $$unsubscribe__();
  return `<h1>${escape($_("team.title"))}</h1> <div class="grid-container svelte-setmz5">${each($_("team.text"), (paragraph) => {
    return `<div class="grid-element svelte-setmz5"><h3>${escape(paragraph.name)}</h3> ${each(paragraph.desc, (line) => {
      return `<p class="svelte-setmz5">${escape(line)}</p>`;
    })} </div>`;
  })}</div> <div class="flex-container svelte-setmz5" data-svelte-h="svelte-1igwiji"><img src="images/assistants.jpg" alt="Assistants" class="svelte-setmz5"> <img src="images/sunee.jpg" alt="Dr. Sunee" class="svelte-setmz5"> </div>`;
});
const css$2 = {
  code: "li.svelte-1bv0euj{font-size:1.5rem}img.svelte-1bv0euj{width:100%;height:250px;object-fit:cover}figcaption.svelte-1bv0euj{margin-bottom:1rem}.grid-container.svelte-1bv0euj{display:grid;grid-template-columns:[row1-start] 50% [row1-end row2-start] 50% [row2-end];justify-content:center}.grid-element.svelte-1bv0euj{margin:1rem}@media screen and (max-width: 720px){.grid-container.svelte-1bv0euj{display:block}}",
  map: '{"version":3,"file":"Technology.svelte","sources":["Technology.svelte"],"sourcesContent":["<script>\\n\\timport { _ } from \\"svelte-i18n\\";\\n<\/script>\\n\\n<h1>{$_(\\"technology.title\\")}</h1>\\n<ul>\\n\\t{#each $_(\\"technology.text\\") as paragraph}\\n\\t\\t<li>{paragraph}</li>\\n\\t{/each}\\n</ul>\\n\\n<div class=\\"grid-container\\">\\n\\t<div class=\\"grid-element\\">\\n\\t\\t<img src=\\"images/itero.jpg\\" alt=\\"iTero Scanner\\">\\n\\t\\t<figcaption>iTero 3D Scanner</figcaption>\\n\\t</div>\\n\\t<div class=\\"grid-element\\">\\n\\t\\t<img src=\\"images/lab-bake.jpg\\" alt=\\"In-house Labratory\\">\\n\\t\\t<figcaption>In-house Labratory</figcaption>\\n\\t</div>\\n\\t<div class=\\"grid-element\\">\\n\\t\\t<img src=\\"images/vatech.jpg\\" alt=\\"CT Scanner\\">\\n\\t\\t<figcaption>CT Scanner</figcaption>\\n\\t</div>\\n\\t<div class=\\"grid-element\\">\\n\\t\\t<img src=\\"images/emax.jpg\\" alt=\\"e.max crown\\">\\n\\t\\t<figcaption>e.max</figcaption>\\n\\t</div>\\n</div>\\n\\n<style>\\n\\tli{\\n\\t\\tfont-size: 1.5rem;\\n\\t}\\n\\timg{\\n\\t\\twidth:100%;\\n\\t\\theight: 250px;\\n\\t\\tobject-fit: cover;\\n\\t}\\n\\tfigcaption{\\n\\t\\tmargin-bottom: 1rem;\\n\\t}\\n\\t.grid-container{\\n\\t\\tdisplay: grid;\\n\\t\\tgrid-template-columns: [row1-start] 50% [row1-end row2-start] 50% [row2-end];\\n\\t\\tjustify-content: center;\\n\\t}\\n\\t.grid-element{\\n\\t\\tmargin: 1rem;\\n\\t}\\n\\t@media screen and (max-width: 720px){\\n\\t\\t.grid-container{\\n\\t\\t\\tdisplay: block;\\n\\t\\t}\\n\\t}\\n</style>"],"names":[],"mappings":"AA+BC,iBAAE,CACD,SAAS,CAAE,MACZ,CACA,kBAAG,CACF,MAAM,IAAI,CACV,MAAM,CAAE,KAAK,CACb,UAAU,CAAE,KACb,CACA,yBAAU,CACT,aAAa,CAAE,IAChB,CACA,8BAAe,CACd,OAAO,CAAE,IAAI,CACb,qBAAqB,CAAE,CAAC,UAAU,CAAC,CAAC,GAAG,CAAC,CAAC,QAAQ,CAAC,UAAU,CAAC,CAAC,GAAG,CAAC,CAAC,QAAQ,CAAC,CAC5E,eAAe,CAAE,MAClB,CACA,4BAAa,CACZ,MAAM,CAAE,IACT,CACA,OAAO,MAAM,CAAC,GAAG,CAAC,YAAY,KAAK,CAAC,CACnC,8BAAe,CACd,OAAO,CAAE,KACV,CACD"}'
};
const Technology = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let $_, $$unsubscribe__;
  $$unsubscribe__ = subscribe($format, (value) => $_ = value);
  $$result.css.add(css$2);
  $$unsubscribe__();
  return `<h1>${escape($_("technology.title"))}</h1> <ul>${each($_("technology.text"), (paragraph) => {
    return `<li class="svelte-1bv0euj">${escape(paragraph)}</li>`;
  })}</ul> <div class="grid-container svelte-1bv0euj" data-svelte-h="svelte-1uspzt3"><div class="grid-element svelte-1bv0euj"><img src="images/itero.jpg" alt="iTero Scanner" class="svelte-1bv0euj"> <figcaption class="svelte-1bv0euj">iTero 3D Scanner</figcaption></div> <div class="grid-element svelte-1bv0euj"><img src="images/lab-bake.jpg" alt="In-house Labratory" class="svelte-1bv0euj"> <figcaption class="svelte-1bv0euj">In-house Labratory</figcaption></div> <div class="grid-element svelte-1bv0euj"><img src="images/vatech.jpg" alt="CT Scanner" class="svelte-1bv0euj"> <figcaption class="svelte-1bv0euj">CT Scanner</figcaption></div> <div class="grid-element svelte-1bv0euj"><img src="images/emax.jpg" alt="e.max crown" class="svelte-1bv0euj"> <figcaption class="svelte-1bv0euj">e.max</figcaption></div> </div>`;
});
const css$1 = {
  code: "img.svelte-h6i230{width:400px}.flex-container.svelte-h6i230{display:flex;justify-content:space-around}@media screen and (max-width: 900px){.flex-container.svelte-h6i230{display:block}img.svelte-h6i230{width:100%}}",
  map: '{"version":3,"file":"Promo.svelte","sources":["Promo.svelte"],"sourcesContent":["<script>\\n\\timport { _ } from \\"svelte-i18n\\";\\n<\/script>\\n\\n<h1>{$_(\\"promo.title\\")}</h1>\\n{#each $_(\\"promo.text\\") as paragraph}\\n\\t<p>{paragraph}</p>\\n{/each}\\n<div class=\\"flex-container\\">\\n\\t<img src=\\"images/zoom.jpg\\" alt=\\"ZOOM Whitening Promotion\\"/>\\n\\t<img src=\\"images/social-security.jpg\\" alt=\\"Social Security Promotion\\"/>\\n</div>\\n\\n<style>\\n\\timg{\\n\\t\\twidth: 400px;\\n\\t}\\n\\t.flex-container{\\n\\t\\tdisplay: flex;\\n\\t\\tjustify-content: space-around;\\n\\t}\\n\\t@media screen and (max-width: 900px){\\n\\t\\t.flex-container{\\n\\t\\t\\tdisplay: block;\\n\\t\\t}\\n\\t\\timg{\\n\\t\\t\\twidth: 100%;\\n\\t\\t}\\n\\t}\\n</style>"],"names":[],"mappings":"AAcC,iBAAG,CACF,KAAK,CAAE,KACR,CACA,6BAAe,CACd,OAAO,CAAE,IAAI,CACb,eAAe,CAAE,YAClB,CACA,OAAO,MAAM,CAAC,GAAG,CAAC,YAAY,KAAK,CAAC,CACnC,6BAAe,CACd,OAAO,CAAE,KACV,CACA,iBAAG,CACF,KAAK,CAAE,IACR,CACD"}'
};
const Promo = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let $_, $$unsubscribe__;
  $$unsubscribe__ = subscribe($format, (value) => $_ = value);
  $$result.css.add(css$1);
  $$unsubscribe__();
  return `<h1>${escape($_("promo.title"))}</h1> ${each($_("promo.text"), (paragraph) => {
    return `<p>${escape(paragraph)}</p>`;
  })} <div class="flex-container svelte-h6i230" data-svelte-h="svelte-v179i"><img src="images/zoom.jpg" alt="ZOOM Whitening Promotion" class="svelte-h6i230"> <img src="images/social-security.jpg" alt="Social Security Promotion" class="svelte-h6i230"> </div>`;
});
const css = {
  code: "img.svelte-a3gpya{width:100%;height:600px;object-fit:cover}.block.svelte-a3gpya{padding:5rem 15%}@media(max-width: 720px){.block.svelte-a3gpya{padding:2rem 2rem}}#services.svelte-a3gpya{background-color:#FFDDDD}#technology.svelte-a3gpya{background-color:#FFDDDD}",
  map: '{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<script>\\n\\timport { _ } from \\"svelte-i18n\\";\\n\\timport { locale } from \\"svelte-i18n\\";\\n\\timport Welcome from \\"./Welcome.svelte\\";\\n\\timport Services from \\"./Services.svelte\\";\\n\\timport Team from \\"./Team.svelte\\";\\n\\timport Technology from \\"./Technology.svelte\\";\\n\\timport Promo from \\"./Promo.svelte\\";\\n\\timport Contact from \\"./Contact.svelte\\";\\n<\/script>\\n\\n<img src=\\"images/building.jpg\\" alt=\\"Asok Montri Dental Clinic Building Picture\\"/>\\n\\n<div class=\\"block\\" id=\\"welcome\\">\\n\\t<Welcome/>\\n</div>\\n\\n<div class=\\"block\\" id=\\"services\\">\\n\\t<Services/>\\n</div>\\n\\n<div class=\\"block\\" id=\\"team\\">\\n\\t<Team/>\\n</div>\\n\\n<div class=\\"block\\" id=\\"technology\\">\\n\\t<Technology/>\\n</div>\\n\\n<div class=\\"block\\" id=\\"promo\\">\\n\\t<Promo/>\\n</div>\\n\\n\\n\\n<style>\\n\\timg{\\n\\t\\twidth: 100%;\\n\\t\\theight: 600px;\\n\\t\\tobject-fit: cover;\\n\\t}\\n\\t.block{\\n\\t\\tpadding: 5rem 15%;\\n\\t}\\n\\t@media (max-width: 720px){\\n\\t\\t.block{\\n\\t\\t\\tpadding: 2rem 2rem;\\n\\t\\t}\\n\\t}\\n\\t#services{\\n\\t\\tbackground-color: #FFDDDD;\\n\\t}\\n\\t#technology{\\n\\t\\tbackground-color: #FFDDDD;\\n\\t}\\n</style>\\n"],"names":[],"mappings":"AAoCC,iBAAG,CACF,KAAK,CAAE,IAAI,CACX,MAAM,CAAE,KAAK,CACb,UAAU,CAAE,KACb,CACA,oBAAM,CACL,OAAO,CAAE,IAAI,CAAC,GACf,CACA,MAAO,YAAY,KAAK,CAAC,CACxB,oBAAM,CACL,OAAO,CAAE,IAAI,CAAC,IACf,CACD,CACA,uBAAS,CACR,gBAAgB,CAAE,OACnB,CACA,yBAAW,CACV,gBAAgB,CAAE,OACnB"}'
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<img src="images/building.jpg" alt="Asok Montri Dental Clinic Building Picture" class="svelte-a3gpya"> <div class="block svelte-a3gpya" id="welcome">${validate_component(Welcome, "Welcome").$$render($$result, {}, {}, {})}</div> <div class="block svelte-a3gpya" id="services">${validate_component(Services, "Services").$$render($$result, {}, {}, {})}</div> <div class="block svelte-a3gpya" id="team">${validate_component(Team, "Team").$$render($$result, {}, {}, {})}</div> <div class="block svelte-a3gpya" id="technology">${validate_component(Technology, "Technology").$$render($$result, {}, {}, {})}</div> <div class="block svelte-a3gpya" id="promo">${validate_component(Promo, "Promo").$$render($$result, {}, {}, {})} </div>`;
});
export {
  Page as default
};
