[build]
	command = "npm run build"
	publish = "build"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"