backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "uploads"

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

site_url: https://asokmontridental.net

collections:
  - name: posts
    identifier_field: name